Navbar
dan933/admin-fe-edable pull request #6
Opened 2022-08-18 04:18 UTC by Waderaide

Added routes & transaction component (mainly for testing can delete later)

Added code for navbar (fonts may need looking at etc)

2022-08-18 04:38 UTC, dan933 approved these changes

2022-08-19 04:53 UTC, AdamDod requested changes
not sure if it's just on my end but the title in the toolbar is not centered?

2022-08-19 04:55 UTC, AdamDod reviewed
also clipping in the toolbar when page width at 615px

2022-08-19 07:36 UTC, dan933 commented on FE/src/app/components/navigation/header/header.component.scss
> +    border-radius: 0;
> also clipping in the toolbar when page width at 615px
`min-width: fit-content;`
can fix the clipping issue

2022-08-22 06:32 UTC, AdamDod approved these changes

2022-08-23 00:02 UTC, merged